### ISSUE TITLE
Update to Gatsby 2

### ISSUE THREAD

**Issue by mckernanin** [reactdenver/reactdenver.com#1]

**Comment by frytyler** [comment]
Given the migration path is fairly intense from [their site](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2) I'd also most suggest starting a new v2 gatsby project and putting the `src` directory from this into it and see how it turns out. Might be the fastest approach to migrate. 

Let me know what you think I could take a stab at that if you want.

**Comment by mckernanin** [comment]
Yeah that sounds like the way to go. Go for it!

**Comment by frytyler** [comment]
Ha so doesn't seem to be as easy as that because of the use of graphql and stuff. Anyway I ran out of time tonight so I might come back to this at some point but if someone else wants to help out all the power to them.

**Comment by mckernanin** [comment]
Thanks! I’ll take a look and see what we can do

**Comment by mckernanin** [comment]
We're working on a rebuild of the site with gatsby 2, closing this issue.
